#Application Configuration
server:
  port: 8091
  error:
    include-message: always
# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/product-service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"